org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.7-hotspot

# Mod Properties
mod_id = emotecraft
mod_name = Emotecraft
mod_version = 2.4.12
maven_group = io.github.kosmx.emotes
archives_base_name = emotecraft-1.12.2-forge

# Minecraft / Forge Properties
mc_version = 1.12.2
forge_version = 14.23.5.2860
mcp_mappings_channel = stable
mcp_mappings_version = 39
